# Generated by Django 5.0.8 on 2024-08-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0115_convert_dashboard_widgets'),
        ('netbox_topology_views', '0009_individualoptions_group_virtualchassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualoptions',
            name='preselected_device_roles',
            field=models.ManyToManyField(blank=True, db_table='netbox_topology_views_individualoptions_prd', related_name='+', to='dcim.devicerole'),
        ),
        migrations.AlterField(
            model_name='individualoptions',
            name='preselected_tags',
            field=models.ManyToManyField(blank=True, db_table='netbox_topology_views_individualoptions_prt', related_name='+', to='extras.tag'),
        ),
        migrations.RenameField(
            model_name='individualoptions',
            old_name='preselected_device_roles',
            new_name='prd',
        ),
        migrations.RenameField(
            model_name='individualoptions',
            old_name='preselected_tags',
            new_name='prt',
        ),
        migrations.RunSQL('alter sequence netbox_topology_views_individualoptions_preselected_devi_id_seq rename to netbox_topology_views_individualoptions_prd_id_seq;'),
        migrations.RunSQL('alter sequence netbox_topology_views_individualoptions_preselected_tag_id_seq rename to netbox_topology_views_individualoptions_prt_id_seq;'),
        


    ]
